#cloud-config
package_update: true
package_upgrade: false
packages:
  - python3
  - python3-apt
ssh_pwauth: false
disable_root: true
users:
  - default
  - name: __SSH_USER__
    groups: [sudo]
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - __SSH_PUBLIC_KEY__
write_files:
  - path: /etc/ssh/sshd_config.d/01-ihetzr.conf
    permissions: "0644"
    owner: root:root
    content: |
      PermitRootLogin no
      PasswordAuthentication no
      PubkeyAuthentication yes
      AllowUsers __SSH_USER__
runcmd:
  - [bash, -lc, "systemctl reload sshd"]
