$ANSIBLE_VAULT;1.1;AES256
37656634626334323033373938323866633637383436623235316262363937323835623139366232
6435306636633536633365333834343866313761346638610a326136643663356538633065663338
33656365306231386239636238353939656633656638613337313039646136633034396130386533
3936383463663132330a326632373434306134646430623739663436383438333265396134363935
63313234386235323639323139386230636333323635303763313864626238613334386162643638
38323138303566303039626461663537616332323431633761623037663235623466346539303766
62356436383938666566373264343461306336303833313562333165626232346665363064613466
37643630623865643735383834663963343130333231303235383633363331306434326139613461
65616463383339356464366236663938336231623933313262316531326336623232303237633935
38383130346231316634656565646266613764383238336362343463616437346161386631393061
31663566313334366436376135343933313466333265653035363865303461313535396231636330
38306237383239626263326436636530386239326330313537306261336632366265643234623766
32623831393636643039373032643733313336656638393265386336646263333632356235336165
63653365613532356237396361326565343439383366323764653335613938303133666664646134
62316562336539636439643366346230323633333438376432663666623866623265343734623738
38613339316132393462326566323162373037633130663165623730373037363966633865666231
62656563356436626232366639356638333730336531636133383266383465316265313363336139
62616365643138393139663536656462623361616530626564666163346161323364386638386366
38656136363039366530653564343565316433333530363434306437316664336536633266626464
38336431363261396561
